//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeraExcelPorAspNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacionar
    {
        public System.Guid Id { get; set; }
        public System.Guid PrecificacaoId { get; set; }
        public System.Guid FormaPagamentoId { get; set; }
        public Nullable<System.Guid> UsuarioCriacaoId { get; set; }
        public Nullable<System.Guid> UsuarioAlteracaoId { get; set; }
        public decimal ValorHora { get; set; }
        public int NumeroVaga { get; set; }
        public string PlacaVeiculo { get; set; }
        public string MarcaVeiculo { get; set; }
        public string ModeloVeiculo { get; set; }
        public Nullable<System.DateTime> DataEntrada { get; set; }
        public Nullable<System.DateTime> DataSaida { get; set; }
        public decimal ValorDevido { get; set; }
        public string TempoDecorrido { get; set; }
        public bool Ativo { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    }
}
